// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A chatbot flow that answers questions about APSAD's mission, projects, and sites.
 *
 * - answerQuestionsAboutAPSAD - A function that handles the question answering process.
 * - AnswerQuestionsAboutAPSADInput - The input type for the answerQuestionsAboutAPSAD function.
 * - AnswerQuestionsAboutAPSADOutput - The return type for the answerQuestionsAboutAPSAD function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerQuestionsAboutAPSADInputSchema = z.object({
  question: z.string().describe('The question to be answered about APSAD.'),
});
export type AnswerQuestionsAboutAPSADInput = z.infer<
  typeof AnswerQuestionsAboutAPSADInputSchema
>;

const AnswerQuestionsAboutAPSADOutputSchema = z.object({
  answer: z.string().describe('The answer to the question about APSAD.'),
});
export type AnswerQuestionsAboutAPSADOutput = z.infer<
  typeof AnswerQuestionsAboutAPSADOutputSchema
>;

export async function answerQuestionsAboutAPSAD(
  input: AnswerQuestionsAboutAPSADInput
): Promise<AnswerQuestionsAboutAPSADOutput> {
  return answerQuestionsAboutAPSADFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerQuestionsAboutAPSADPrompt',
  input: {schema: AnswerQuestionsAboutAPSADInputSchema},
  output: {schema: AnswerQuestionsAboutAPSADOutputSchema},
  prompt: `You are a chatbot that answers questions about APSAD, an NGO focused on historical preservation.

  Answer the following question about APSAD:
  {{question}}`,
});

const answerQuestionsAboutAPSADFlow = ai.defineFlow(
  {
    name: 'answerQuestionsAboutAPSADFlow',
    inputSchema: AnswerQuestionsAboutAPSADInputSchema,
    outputSchema: AnswerQuestionsAboutAPSADOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
